#!/bin/bash

#SBATCH --time=10:00:00
#SBATCH --ntasks-per-node=24
#SBATCH --nodes=4
#SBATCH --wckey edu_res
#SBATCH -J "Cheemz Test 0"
#SBATCH --mail-user=spd5822@psu.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END

#SBATCH --chdir=/storage/work/irj5023/NUCE403


module load anaconda3
conda config --add channels conda-forge 
eval "$(conda shell.bash hook)"
conda activate openmc-env
python 	depletion_Code_HFP_ACI.py